import { Product } from '@/types';

export const PRODUCTS: Product[] = [
  {
    id: 'punch-ananas-passion',
    name: 'Punch Ananas-Passion',
    slug: 'punch-ananas-passion',
    tagline: 'Tropical et ensoleill\u00e9',
    description: 'Un mariage tropical entre la douceur de l\'ananas et l\'intensité du fruit de la passion. Notes exotiques, finale vive et ensoleillée.',
    price_cents: 2500,
    alcohol_degree: 15,
    volume_ml: 700,
    flavor: 'Ananas, Passion',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    is_featured: true,
    ingredients: ['Ananas', 'Sirop de la passion', 'Sirop de cannes', 'Rhum', 'Arômes'],
    tasting_tips: 'Servir bien frais (8-10°C). Idéal en apéritif ou avec un dessert aux fruits exotiques.',
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-ananas-goyave',
    name: 'Punch Ananas-Goyave',
    slug: 'punch-ananas-goyave',
    tagline: 'Doux et fruit\u00e9',
    description: 'L\'ananas rencontre la goyave dans un punch genereux aux aromes tropicaux. Doux, fruité, irresistible.',
    price_cents: 2500,
    alcohol_degree: 15,
    volume_ml: 700,
    flavor: 'Ananas, Goyave',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    is_featured: true,
    ingredients: ['Ananas', 'Goyave', 'Sirop de cannes', 'Rhum', 'Arômes'],
    tasting_tips: 'Servir frais sur glace pilée. Parfait pour accompagner un accra ou un gratin de christophines.',
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-passion',
    name: 'Punch Passion',
    slug: 'punch-passion',
    tagline: 'Vif et exotique',
    description: 'Toute l\'intensité du fruit de la passion dans un punch vif et parfume. Acidule, exotique, addictif.',
    price_cents: 2500,
    alcohol_degree: 15,
    volume_ml: 700,
    flavor: 'Passion',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    is_featured: true,
    ingredients: ['Fruit de la passion', 'Sirop de cannes', 'Rhum', 'Arômes'],
    tasting_tips: 'Servir glacé, nature ou allongé d\'un trait de jus de citron vert. Explosif en cocktail.',
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-coco',
    name: 'Punch Coco',
    slug: 'punch-coco',
    tagline: 'Cr\u00e9meux et rond',
    description: 'La douceur onctueuse du lait de coco mariee au rhum des iles. Cremeux, rond, un voyage sous les cocotiers.',
    price_cents: 2500,
    alcohol_degree: 15,
    volume_ml: 700,
    flavor: 'Coco',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    ingredients: ['Lait de coco', 'Lait', 'Sirop de cannes', 'Rhum', 'Arômes'],
    tasting_tips: 'Servir très frais, voire sur glace. Onctueux en digestif ou pour accompagner un flan coco.',
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-pili-pili',
    name: 'Punch Pili-Pili',
    slug: 'punch-pili-pili',
    tagline: '\u00c9pic\u00e9 et audacieux',
    description: 'Un punch audacieux aux epices relevees et au sirop de grenade. Piquant, chaleureux, une explosion de caractere.',
    price_cents: 2500,
    alcohol_degree: 15,
    volume_ml: 700,
    flavor: 'Pili-Pili',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    ingredients: ['Épices diverses', 'Sirop de grenade', 'Rhum', 'Arômes'],
    tasting_tips: 'Servir frais en petites doses. Se marie à merveille avec un boudin créole ou des beignets de morue.',
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-coco-gingembre',
    name: 'Punch Coco-Gingembre',
    slug: 'punch-coco-gingembre',
    tagline: 'Velout\u00e9 et relev\u00e9',
    description: 'Le veloute du coco rehausse par la vivacite du gingembre frais. Epice, cremeux, un equilibre parfait.',
    price_cents: 2500,
    alcohol_degree: 15,
    volume_ml: 700,
    flavor: 'Coco, Gingembre',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    ingredients: ['Lait de coco', 'Lait', 'Gingembre', 'Sirop de cannes', 'Rhum', 'Arômes'],
    tasting_tips: 'Servir frais. Le gingembre réchauffe, le coco adoucit — parfait en soirée autour d\'un ti-bois.',
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-goyave',
    name: 'Punch Goyave',
    slug: 'punch-goyave',
    tagline: 'Sucr\u00e9 et parfum\u00e9',
    description: 'La goyave des Caraibes dans toute sa splendeur. Sucre, parfume, un classique tropical revisité.',
    price_cents: 2500,
    alcohol_degree: 15,
    volume_ml: 700,
    flavor: 'Goyave',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    ingredients: ['Goyave', 'Sirop de cannes', 'Rhum', 'Arômes'],
    tasting_tips: 'Servir bien frais, nature. Un classique des apéros créoles, sucré et généreux.',
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-mangue-ananas',
    name: 'Punch Mangue-Ananas',
    slug: 'punch-mangue-ananas',
    tagline: 'Gourmand et g\u00e9n\u00e9reux',
    description: 'Deux fruits solaires reunis dans un punch gourmand et genereux. Sucre, tropical, une invitation au voyage.',
    price_cents: 2500,
    alcohol_degree: 15,
    volume_ml: 700,
    flavor: 'Mangue, Ananas',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    ingredients: ['Mangue', 'Ananas', 'Sirop de cannes', 'Rhum', 'Arômes'],
    tasting_tips: 'Servir glacé. Gourmand et solaire, idéal pour un brunch tropical ou un dessert fruité.',
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-litchis',
    name: 'Punch Litchis',
    slug: 'punch-litchis',
    tagline: 'Floral et d\u00e9licat',
    description: 'La delicatesse du litchi dans un punch floral et rafraichissant. Subtil, parfume, une douceur exotique.',
    price_cents: 2500,
    alcohol_degree: 15,
    volume_ml: 700,
    flavor: 'Litchis',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    ingredients: ['Litchis', 'Sirop de cannes', 'Rhum', 'Arômes'],
    tasting_tips: 'Servir très frais en flûte ou petit verre. Délicat et floral, parfait en apéritif élégant.',
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'coffret-decouverte',
    name: 'Coffret Découverte',
    slug: 'coffret-decouverte',
    tagline: 'L\'essentiel des saveurs',
    description: 'Trois punchs emblématiques réunis dans un coffret cadeau élégant. Idéal pour découvrir l\'univers Bô Kay Mwen ou pour offrir un voyage gustatif aux Antilles.',
    price_cents: 6500,
    alcohol_degree: 15,
    volume_ml: null,
    flavor: null,
    image_url: null,
    stock_quantity: 10,
    is_active: true,
    is_featured: false,
    category: 'coffret',
    pack_contents: ['Punch Ananas-Passion', 'Punch Coco', 'Punch Passion'],
    tasting_tips: 'Déguster chaque punch bien frais, dans l\'ordre : Coco, Ananas-Passion, puis Passion pour finir sur une note vive.',
    volume: '3 × 70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'coffret-prestige',
    name: 'Coffret Prestige',
    slug: 'coffret-prestige',
    tagline: 'L\'intégrale des Caraïbes',
    description: 'L\'expérience complète : cinq punchs sélectionnés pour un tour des saveurs caribéennes. Le cadeau parfait pour les amateurs de belles découvertes.',
    price_cents: 10000,
    alcohol_degree: 15,
    volume_ml: null,
    flavor: null,
    image_url: null,
    stock_quantity: 5,
    is_active: true,
    is_featured: false,
    category: 'coffret',
    pack_contents: ['Punch Ananas-Passion', 'Punch Coco', 'Punch Passion', 'Punch Goyave', 'Punch Pili-Pili'],
    tasting_tips: 'Commencer par les notes douces (Coco, Goyave), puis monter en intensité (Ananas-Passion, Passion) et terminer par le Pili-Pili épicé.',
    volume: '5 × 70cl',
    created_at: new Date().toISOString(),
  },
];

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter(p => p.is_featured).slice(0, 3);
}

export function getAllProducts(): Product[] {
  return PRODUCTS.filter(p => p.is_active);
}

export function getProductBySlug(slug: string): Product | null {
  return PRODUCTS.find(p => p.slug === slug) || null;
}
